import { title } from "process";
import React from "react";
const products  = [
  {
    id: 0,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/product-cover-5.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 1,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/fixed-height (1).png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 2,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/fixed-height (2).png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 3,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/fixed-height (3).png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 4,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/fixed-height.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 5,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/fixed-height (4).png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 6,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/fixed-height (5).png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 7,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/fixed-height (6).png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 8,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p9.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 9,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p10.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 10,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p11.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 11,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p12.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 12,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p12.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  
];
export default products