import { title } from "process";
import React from "react";
const  BestProductsdata  = [
  {
    id: 0,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/B1.PNG",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 1,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/B2.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 2,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/B3.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 3,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/B4.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 4,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/B5.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 5,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/B6.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 6,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/B7.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 7,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/B8.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 8,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p9.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 9,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p10.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 10,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p11.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 11,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p12.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  {
    id: 12,
    title: "Graphic Design",
    desc: "English Department",
    img: "/images/p12.png",
    price: '$6.48',
    originalPrice: '$16.48',
  },
  
];
export default BestProductsdata